name: static-site

type: nodejs:12

disk: 1024

web:
  locations:
    "/":
      root: "public"
      allow: true
      scripts: false
      expires: 5m
      index:
        - index.html
      rules:
                # Allow access to common static files.
                '(?i)\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                    headers:
			Access-Control-Allow-Origin: "*"
			Access-Control-Allow-Credentials: "*"
			Access-Control-Allow-Headers: "X-Requested-With"
                '^/robots\.txt$':
                    allow: true
		    headers:
                        Access-Control-Allow-Origin: "*"
                        Access-Control-Allow-Credentials: "*"
                        Access-Control-Allow-Headers: "X-Requested-With"
                '^/sitemap\.xml$':
                    allow: true
		    headers:
                        Access-Control-Allow-Origin: "*"
                        Access-Control-Allow-Credentials: "*"
                        Access-Control-Allow-Headers: "X-Requested-With"
