name: static-site

type: nodejs:12

disk: 1024

web:
  locations:
    "/":
      root: "public"
      allow: true
      scripts: false
      index:
        - index.html
      rules:
                '(?i)\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true
